CUDA_VISIBLE_DEVICES=5 python train_ctrl.py \
    --model_name_or_path fnlp/bart-base-chinese \
    --do_train \
    --do_eval \
    --do_predict \
    --train_file ./datasets/dulemon/train.csv \
    --validation_file ./datasets/dulemon/dev.csv \
    --test_file ./datasets/dulemon/test.csv \
    --input_column history \
    --target_column target \
    --control_columns Gender,Emotion,Question \
    --control_mapping_path ./aux_files/control_token_mapping_3aspect.json \
    --control_condition_type condition \
    --max_source_length 384 \
    --pad_to_max_length \
    --input_truncation_side left \
    --max_target_length 128 \
    --num_beams 1 \
    --learning_rate 3e-5 \
    --num_train_epochs 6 \
    --evaluation_strategy epoch \
    --save_strategy epoch \
    --save_total_limit 1 \
    --metric_for_best_model bert_score_f1 \
    --greater_is_better true \
    --load_best_model_at_end \
    --fp16 \
    --predict_with_generate \
    --output_dir ./train_dulemon_outputs/bart_condition1 \
    --overwrite_cache \
    --overwrite_output_dir \
    --per_device_train_batch_size 48 \
    --per_device_eval_batch_size 48